Add homework for Module-1
Idea-Pool/js-webinar pull request #13
Opened 2018-04-22 18:06 UTC by lusinehak

2018-04-27 10:04 UTC, szikszail requested changes

2018-04-27 10:04 UTC, szikszail commented on module-1/euclidean.js
> +        gcd = euclidean(b, a % b);
Interesting approach. It works, in some cases, not the most optimal one, e.g. if the function called with b > a, it will have an unnecessary call, with `euclidean(b, a)`. And also, the exception checking is done in most cases which should be done only once.

2018-04-27 10:04 UTC, szikszail commented on module-1/classification.js
> +    } else if(score >= 80 && score <= 89) {
Are all conditions necessary in all cases?

2018-05-21 17:31 UTC, lusinehak reviewed
Corrected homework for module-1. Added home works for module-2 - module-4

2018-07-23 22:25 UTC, szikszail commented on module-3/Element.js
> +       } else {
I would also check if any children has a child named as name

2018-07-23 22:25 UTC, szikszail commented on module-3/Elements.js
> +        if (child instanceof Elements) {
Actually, this method should throw an error by default. No element should be added as children.

2018-07-23 22:27 UTC, szikszail commented on module-3/Layout.js
> +        if(parent instanceof Layout) {
This method should throw an error in any case :) The layout if the top of the whole hierarchy.

2018-07-23 22:28 UTC, szikszail commented on module-4/arrayEqual.js
> +     if (first[0] !== second[0] && typeof first[0] !== "object"){
Why do you handle this case separately?

2018-07-23 22:29 UTC, szikszail approved these changes
Good job! Although please check my comment :)

2018-07-23 22:29 UTC, closed without merging