added solutions for the first module
Idea-Pool/js-webinar pull request #14
Opened 2018-04-23 13:51 UTC by maksimlesko

2018-04-27 10:07 UTC, szikszail requested changes

2018-04-27 10:07 UTC, szikszail commented on module-1/classification.js
> +    } else if (score < 90 && score >= 80) {
Are all conditions necessary in all cases?

2018-04-27 10:07 UTC, szikszail commented on module-1/euclidean.js
> +        gcd = euclidean(b, a % b);
Interesting approach, I have seen it from a couple of you Guys :) It works, in some cases, not the most optimal one, e.g. if the function called with b > a, it will have an unnecessary call, with `euclidean(b, a)`. And also, the exception checking is done in most cases which should be done only once.

2018-04-27 10:07 UTC, szikszail commented on module-1/fibonacci.js
> +    n < 0 ? nThFibonacci = 0 : n < 2 ? nThFibonacci = n : nThFibonacci = fibonacci(n - 1) + fibonacci (n - 2)
Putting assignment in a conditional expression is an anti-pattern. Could you please refactor them?

2018-05-16 10:45 UTC, szikszail requested changes

2018-05-16 10:45 UTC, szikszail commented on module-1/classification.js
> +    return score < 0 || score > 100 ? 0 : score < 60 ? 1 : score == 100 ? 5 : 1 + grade( score - 10)
I have seen this solution somewhere... :P

2018-05-16 10:45 UTC, szikszail commented on module-1/euclidean.js
> +    while (b !== 0) {
Is this the complete solution?

2018-05-16 10:45 UTC, szikszail commented on module-2/test/calc.spec.js
> +        it ('should perform a complex scenario and store every intermediate result', () => {
I think here, it would be better if you would test whether these operations can be chained together too.

2018-05-16 11:46 UTC, maksimlesko commented on module-1/euclidean.js
> +    while (b !== 0) {
Hi Laszlo,

Please ignore the whole module 1 from me, I've pushed it accidentally.
Will send you another one, sorry for the inconvenience.

2018-05-16 11:46 UTC, maksimlesko commented on module-1/classification.js
> +    return score < 0 || score > 100 ? 0 : score < 60 ? 1 : score == 100 ? 5 : 1 + grade( score - 10)
Hi Laszlo,

Please ignore the whole module 1 from me, I've pushed it accidentally.
Will send you another one, sorry for the inconvenience.

2018-07-23 22:22 UTC, szikszail approved these changes
Good job! I would really see your solution for the Page Object tasks :)

2018-07-23 22:22 UTC, closed without merging