Aliaksandr_Khatsko_Module-1
Idea-Pool/js-webinar pull request #16
Opened 2018-04-25 08:21 UTC by AliaksandrKhatsko

2018-04-27 10:21 UTC, szikszail requested changes

2018-04-27 10:21 UTC, szikszail commented on module-1/classification.js
> +  if (score >= 90 && score <= 100) {
In this implementation, all conditions will be evaluated. Could you please make it more optimal?

2018-04-27 10:21 UTC, szikszail commented on module-1/fibonacci.js
> +      current = nThFibonacci;
Are all variables necessary?

2018-05-06 19:39 UTC, AliaksandrKhatsko commented on module-1/classification.js
> +  if (score >= 90 && score <= 100) {
Corrected to use else if instead of if statements

2018-05-06 19:40 UTC, AliaksandrKhatsko commented on module-1/fibonacci.js
> +      current = nThFibonacci;
Updated Fibonacci function to use recursion

2018-05-06 19:40 UTC, AliaksandrKhatsko commented
Updated module-1 tasks in regard to comments.

2018-05-16 10:08 UTC, AliaksandrKhatsko commented
Update tasks with requested changes

2018-05-16 10:40 UTC, szikszail requested changes

2018-05-16 10:40 UTC, szikszail commented on module-1/euclidean.js
> +  if (a === 0) {
According to the requirements of this function, it must return 0 in case any of the parameters is less or equal than 0.
If you call this function like this: `gcd(0, 12)`, it will return 12, but is must return 0.

2018-05-16 10:40 UTC, szikszail commented on module-2/test/calc.spec.js
> +  it('should return intital value', () => {
Nice!

2018-05-16 10:40 UTC, szikszail commented on module-1/classification.js
> +  if (score >= 90 && score <= 100) {
You can simplify it even more, I think some of your conditions are not necessary.

2018-05-16 15:31 UTC, AliaksandrKhatsko commented on module-1/classification.js
> +  if (score >= 90 && score <= 100) {
Simplified conditions even more.

2018-05-16 15:33 UTC, AliaksandrKhatsko commented on module-1/euclidean.js
> +  if (a === 0) {
gcd of number and zero should return number according to Wikipedia. I have added a condition to check if b === 0 gcd should be equal a.

2018-05-16 15:34 UTC, AliaksandrKhatsko commented
Corrected according to last comments.

2018-07-23 22:17 UTC, szikszail commented on module-1/euclidean.js
> +  if (a === 0) {
Right :)

2018-07-23 22:18 UTC, szikszail approved these changes
Good job!

2018-07-23 22:18 UTC, closed without merging