adding module-1 solutions
Idea-Pool/js-webinar pull request #21
Opened 2019-03-13 09:20 UTC by zsbolgar

2019-04-01 19:11 UTC, szikszail requested changes
Good job! Please check my comments to make it better :)

2019-04-01 19:11 UTC, szikszail commented on module-1/classification.js
> +    gradeOfStudent = (score < 0 || score > 100) ? 0 : (score >= 90) ? 5 : (score >= 80) ? 4 : (score >= 70) ? 3 : (score >= 60) ? 2 : 1;
Clever, but you can make a shorter mathematical expression, could you think about that?

2019-04-01 19:11 UTC, szikszail commented on module-2/test/calc.spec.js
> +        expect(() => c.sqrt(-3)).to.throw;
As far as I remember `sqrt` does not accept any argument :)

2019-04-01 19:11 UTC, szikszail commented on module-3/Element.js
> +            return this.children[Object.keys(this.children)[0]].get(name);
In this case it would be better to iterate over all children and search for the sub-element.

2019-04-01 19:11 UTC, szikszail commented on module-3/HomePage.js
> +        this.title = new Element('Title', { css: '.title' });
Setting the locator might work in this way, but I would stick using `by.css`.

2019-04-01 19:11 UTC, szikszail commented on module-3/HomePage.js
> +        super.addChildren(this.title);
You can use `this.addChildren`, since this class inherits parent's methods and it can use it as its own.

2019-04-01 19:11 UTC, szikszail commented on module-3/HomePage.js
> +        this.title.setParent(this);
You could also add this login to `addChildren`, that it sets the parent of the child as well.

2019-04-01 19:11 UTC, szikszail commented on module-3/HomePage.js
> +        return 'title text';
You can use `browser.getTitle()`

2019-04-02 09:21 UTC, zsbolgar commented on module-1/classification.js
> +    gradeOfStudent = (score < 0 || score > 100) ? 0 : (score >= 90) ? 5 : (score >= 80) ? 4 : (score >= 70) ? 3 : (score >= 60) ? 2 : 1;
ok. another version uploaded.

2019-04-02 09:22 UTC, zsbolgar commented on module-2/test/calc.spec.js
> +        expect(() => c.sqrt(-3)).to.throw;
fixed

2019-04-02 09:22 UTC, zsbolgar commented on module-3/Element.js
> +            return this.children[Object.keys(this.children)[0]].get(name);
new solution uploaded

2019-04-02 09:22 UTC, zsbolgar commented on module-3/HomePage.js
> +        super.addChildren(this.title);
fixed

2019-04-02 09:23 UTC, zsbolgar commented on module-3/HomePage.js
> +        this.title.setParent(this);
fixed

2019-04-02 09:24 UTC, zsbolgar commented on module-3/HomePage.js
> +        return 'title text';
Sorry. I don't have browser.getTitle() in the /mock/browser.js

2019-04-02 10:01 UTC, zsbolgar commented on module-3/HomePage.js
> +        this.title = new Element('Title', { css: '.title' });
Bit confused here now. In the Element.spec.js, Layout.spec.js we are using our own Element format for locators. I've thought that i should use these classes in HomePage.js as well.

2019-04-02 21:01 UTC, szikszail requested changes
Nice job. I am looking forward to your solutions for module-4 and 5. (I don't approve it, so that you can put those here.)

2019-04-02 21:01 UTC, szikszail commented on module-3/HomePage.js
> +        this.title = new Element('Title', { css: '.title' });
You are right, I've made mistake when created mocks :) It is OK like this.

2019-04-02 21:01 UTC, szikszail commented on module-3/HomePage.js
> +        return 'title text';
Right. You can add it if you wish, it is the method in protractor to get title of the page.

2019-04-17 07:15 UTC, szikszail commented on module-1/classification.js
> +    gradeOfStudent = (score < 0 || score > 100) ? 0 : Math.max(1, Math.min(5, Math.floor(score / 10) - 4));
You can also limit the input number by `max` and `mix`. But it is also a great solution like this. It is a badge. Please ping me on S4B.

2019-04-17 07:15 UTC, szikszail commented on module-3/Element.js
> +        else {
`else` is not necessary, since all paths before terminating the function if true.

2019-04-17 07:15 UTC, szikszail commented on module-4/arrayEqual.js
> +function arrayEqual(first, second) {
What if they are not arrays?

2019-04-17 07:15 UTC, szikszail commented on module-4/arraySorted.js
> +    result = arrayEqual(originalArray, orderedArray);
Is there a more simple way to check whether two arrays are the same?

2019-04-17 07:15 UTC, szikszail commented on module-4/longestString.js
> +    inputStrings.sort(function (a, b) {
What is the array contains not just strings?

2019-04-17 07:15 UTC, szikszail commented on module-5/pages/careerPage.js
> +        element.all(by.css('.select2-results__options.open[role=listbox][id] [role]')).isDisplayed();
What is the purpose of this statement here?

2019-04-17 07:49 UTC, zsbolgar commented on module-3/Element.js
> +        else {
You are right, i'm fixing

2019-04-17 08:30 UTC, zsbolgar commented on module-4/arraySorted.js
> +    result = arrayEqual(originalArray, orderedArray);
Ok. I hope this new one is what you thought.

2019-04-17 08:35 UTC, zsbolgar commented on module-4/arrayEqual.js
> +function arrayEqual(first, second) {
You are right, i'm fixing.

2019-04-17 09:02 UTC, zsbolgar commented on module-4/longestString.js
> +    inputStrings.sort(function (a, b) {
What is our expectation? If I return empty string in this case (array contains not just strings) then test with boolean input parameter 'True' will fails. Or String and Boolean array items are could be acceptable?

2019-04-17 09:19 UTC, zsbolgar commented on module-5/pages/careerPage.js
> +        element.all(by.css('.select2-results__options.open[role=listbox][id] [role]')).isDisplayed();
With test data of 'Belarus, Minsk' i get 'Element is not clickable at point (854, 161). Other element would receive the click:'. So there was a need to wait to load all items of drop-down list. With browser.wait() i didn't succeed to achieve this so i used the built-in wait of promise in the isDisplayed() function.

2019-08-06 19:22 UTC, szikszail approved these changes
Good solutions. If you'll check my further comments, that would be great, but not mandatory. (I'll close this PR, but don't merge it :)) Thank you!

2019-08-06 19:22 UTC, szikszail commented on module-4/longestString.js
> +    inputStrings.sort(function (a, b) {
I'd ignore the non-string items. I'd filter the array for strings first, and then sort it as you did (but don't forget to return :)).

2019-08-06 19:22 UTC, szikszail commented on module-5/pages/careerPage.js
> +        element.all(by.css('.select2-results__options.open[role=listbox][id] [role]')).isDisplayed();
That error could mean either the wrong element is located or simply there is an overlapping item. It can be a nice hack, which works now, but I next versions of Protractor it won't work. I'd check why wait did not work.

2019-08-06 19:22 UTC, closed without merging