Solutions
Idea-Pool/js-webinar pull request #22
Opened 2019-03-13 14:07 UTC by edsdame

2019-04-01 19:03 UTC, szikszail requested changes
Please check my comment. Are you planning to submit your solution for Module 3?

2019-04-01 19:03 UTC, szikszail commented on module-1/classification.js
> +    gradeOfStudent = score < 60 ? 1 : Math.floor((score-50)/10)+1 - Math.floor(score/100);
You can actually combine the condition to this expression.

2019-04-02 06:21 UTC, edsdame commented on module-1/classification.js
> +    gradeOfStudent = score < 60 ? 1 : Math.floor((score-50)/10)+1 - Math.floor(score/100);
Hi! I want to submit solution to mod3 too, but I need to first rewatch the last part of the webinar too, because I have some unclear parts. The video is not submitted yet.

2019-04-17 07:22 UTC, szikszail commented on module-1/classification.js
> +    gradeOfStudent = (score < 0 || score >100) ? 0 : score < 60 ? 1 : Math.floor((score-50)/10)+1 - Math.floor(score/100);
You can also use `min` and `max` to limit the input score. But it is also a good solution. Please contact me on S4B.

2019-04-17 07:22 UTC, szikszail commented on module-4/arraySorted.js
> +    for (let i = 0; i < items.length; i++) {
What other function of an array can you use for this, to check whether some element of the array matches a criteria?

2019-04-17 07:22 UTC, szikszail commented on module-4/arraySorted.js
> +    if (items.toString() == copiedArray.sort().toString()) return true;
Nice check.
Could you still shorten this `if-return`?

2019-04-17 07:22 UTC, szikszail commented on module-4/arraySum.js
> +let sum = 0;
Do you need this variable? Can this be solved without it?

2019-04-17 07:22 UTC, szikszail commented on module-4/longestString.js
> +        else if (strings[i].length == longestString.length && strings[i] < longestString || longestString.length == 0)
Do you need this branch?

2019-04-17 08:12 UTC, edsdame commented on module-4/arraySorted.js
> +    for (let i = 0; i < items.length; i++) {
Yes, come to think of it. :) Commited the solution.

2019-04-17 08:13 UTC, edsdame commented on module-4/arraySorted.js
> +    if (items.toString() == copiedArray.sort().toString()) return true;
Couldn't think of a shorter way. Can you give a hint?

2019-04-17 08:15 UTC, edsdame commented on module-4/arraySum.js
> +let sum = 0;
If you ask, it probably could, but I couldn't find a better way. Can you show me?

2019-04-17 08:16 UTC, edsdame commented on module-4/longestString.js
> +        else if (strings[i].length == longestString.length && strings[i] < longestString || longestString.length == 0)
Not this way, no. Got rid of the unneccessary "else".

2019-08-06 19:36 UTC, szikszail approved these changes
Thank you for your solutions. If you check the comments which I left that would be great, but ofc not mandatory. (I close the PR, but won't merge it)

2019-08-06 19:36 UTC, szikszail commented on module-4/arraySorted.js
> +    if (items.toString() == copiedArray.sort().toString()) return true;
Maby if is not necessary at all, considering what you return.

2019-08-06 19:36 UTC, szikszail commented on module-4/arraySum.js
> +let sum = 0;
I wouldn't put it outside the function but inside it. And then you don't need `tmp` at all and don't need to zero it all the time.

2019-08-06 19:36 UTC, szikszail commented on module-4/longestString.js
> +    if (typeof strings != 'object') return longestString;
It is better to check it like this: `Array.isArray(strings)`

2019-08-06 19:36 UTC, szikszail commented on module-4/longestString.js
> +    longestString = "";
I would not use a variable, named exactly as the function :) It works, but still confusing, especially without a `let` keyword.

2019-08-06 19:36 UTC, szikszail commented on module-4/longestString.js
> +        }
I'd have an `else-if` here

2019-08-06 19:36 UTC, szikszail commented on module-4/longestString.js
> +       if (strings[i].length == longestString.length && strings[i] < longestString || longestString.length == 0)
Do you need to check for empty `longestString`? If it is still empty, then the previous `if` will set its value, so actually it won't ever be empty at this point.

2019-08-06 19:36 UTC, szikszail commented on module-4/toCamelCase.js
> +        if (ignore.includes(word));
I think `return !ignore.includes(word)` would be shorter instead of the whole `if-else`

2019-08-06 19:36 UTC, szikszail commented on module-4/toCamelCase.js
> +        let words = toConvert[i].split("").map(a => filterword(a)).join("");
Here you use the `filterword` for characters as well, that is a bit confusing.

2019-08-06 19:36 UTC, closed without merging