Solution for classification task in module 1
Idea-Pool/js-webinar pull request #25
Opened 2019-07-25 06:39 UTC by terahekir

2019-07-25 06:54 UTC, terahekir commented
Hi @szikszail, please review

2019-08-06 19:40 UTC, szikszail requested changes
If you'll add solutions for other tasks, I'd be happy to review them as well.

2019-08-06 19:40 UTC, szikszail commented on module-1/classification.js
> +        gradeOfStudent = score < 0 || score > 100 ? 0 : Math.max(Math.min(Math.floor((score-40)/10),5),1);
Nice solution. Please ping me on Skype4Business for your badge.

2020-01-14 19:26 UTC, szikszail commented
Thank you for your solution!

2020-01-14 19:26 UTC, closed without merging