<yauheni-nestserau-solution-for-review>
Idea-Pool/js-webinar pull request #26
Opened 2019-07-29 12:54 UTC by yauheni-nestserau

Please review solution for the first module @szikszail

2019-08-06 19:42 UTC, szikszail requested changes
If you'll finish the task, I'd be happy to review your final solutions.

2019-08-06 19:42 UTC, szikszail commented on module-1/classification.js
> +    else if (score >= 90 & score <=100) {
Do you need to check whether it is less or equal than 100 here?

2019-08-06 19:42 UTC, szikszail commented on module-1/classification.js
> +    else if (score >= 80 & score <=89 ) {
Do you need to check whether it is less than 90 here?

2019-08-06 19:42 UTC, szikszail commented on module-1/classification.js
> +    else if (score >= 70 & score <=79 ) {
Do you need to check... I think you know what I mean :D

2019-08-07 08:19 UTC, yauheni-nestserau reviewed
@szikszail could you please review solution for module2?

2019-08-10 13:26 UTC, szikszail requested changes
Please check my comments.

2019-08-10 13:26 UTC, szikszail commented on module-1/classification.js
> +    else if (score >= 0) {
I think you can spare this condition here since if the execution is here, it is 100% that score is >=0

2019-08-10 13:26 UTC, szikszail commented on module-2/test/calc.spec.js
> +            expect(() => d.sqrt(-3)).to.throw();
`sqrt` does not accept any parameter

2019-08-11 18:15 UTC, yauheni-nestserau reviewed
@szikszail please check updated solutions for modules 1 and 2. Thank you!

2020-01-14 19:34 UTC, szikszail approved these changes
Thank you for your solution!

2020-01-14 19:34 UTC, szikszail commented on module-4/arraySorted.js
> +function arraySorted(items, ignore) {
I don't see, where you are using the `ignore` in the function.

2020-01-14 19:34 UTC, szikszail commented on module-4/arraySorted.js
> +    if (JSON.stringify(prettyArr) === JSON.stringify(prettyArr.sort())) {
I think it would be better if you would just return with this expression.

2020-01-14 19:34 UTC, closed without merging