Solutions for Classification, Euclidean, Fibonacci task in Module-1
Idea-Pool/js-webinar pull request #27
Opened 2019-07-29 17:56 UTC by olga-mashnitskaya

Hello @szikszail, please review the solutions for the first module.

2019-08-06 19:45 UTC, szikszail requested changes
Seems to be good solutions, but without formatting it is not too readable. Could you please format your code? In VSCode, it is `Alt + Shift + F`

2019-08-06 19:45 UTC, szikszail commented on module-1/classification.js
> +if(score >= 0 && score <= 100){
Could you please format it a bit better to make it more readable?

2019-08-06 20:11 UTC, olga-mashnitskaya commented on module-1/classification.js
> +if(score >= 0 && score <= 100){
Thank you for the point. I have solved the issue.

2019-08-10 13:24 UTC, szikszail reviewed
Nice solutions! I am waiting for further implementations.

2019-08-13 16:15 UTC, olga-mashnitskaya commented
Hello @szikszail, could you please help me with the task in Element module? I am unaware how to continue. 
I am also unaware why my tests on addChildren method in Layout class do not pass although I have extended it from Element class.
Thatnk you!

2019-08-13 18:15 UTC, olga-mashnitskaya commented
No problem with addChildren method in Layout class after Element module import.

2019-08-13 19:32 UTC, szikszail requested changes
Please check my comments. I am excited to see the rest of the implementation :)

2019-08-13 19:32 UTC, szikszail commented on module-3/Element.js
> +            throw new Error('No child with such a name')
What if a child has a child named as the parameter? :)

2019-08-13 19:32 UTC, szikszail commented on module-3/Element.js
> +            return this.element(this.locator);
I see your intention. It is actually a good idea to base such method which is Protractor's element method.

2019-08-15 17:58 UTC, olga-mashnitskaya commented on module-3/Element.js
> +            return this.element(this.locator);
Now, with the updates all tests are passed.

2019-08-19 15:23 UTC, szikszail requested changes

2019-08-19 15:23 UTC, szikszail commented on module-1/classification.js
> +    if (score >= 0 && score <= 100) { gradeOfStudent = Math.min(Math.max(Math.ceil((score - 49) / 10), 1), 5) } else { gradeOfStudent = 0 };
Almost :) You can also use [conditional operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)

2019-08-19 15:23 UTC, szikszail commented on module-3/Element.js
> +        }
What if any children have a child named like the parameter?

2019-08-19 15:23 UTC, szikszail commented on module-3/Elements.js
> +        return num;
Here [this](https://www.protractortest.org/#/api?view=ElementArrayFinder.prototype.get) would be the right function to use.

2019-08-19 15:23 UTC, szikszail commented on module-3/HomePage.js
> +class HomePage extends Layout, Element{
I can and is should only extend one class. Here `Layout` would be the right one

2020-01-14 19:34 UTC, szikszail commented
Thank you for your solution!

2020-01-14 19:34 UTC, closed without merging