First module completed
Idea-Pool/js-webinar pull request #29
Opened 2019-07-30 18:09 UTC by MariaShymko

@szikszail Could you please review my task? Thank you!

2019-08-06 19:52 UTC, szikszail requested changes
Please check my comment. I'd be happy to review your other solutions.

2019-08-06 19:52 UTC, szikszail commented on module-1/classification.js
> +	    gradeOfStudent = Math.floor(0.1*score - 4);
If you continue the thread you started here, you can easily make a 1 line mathematical expression.

2019-08-07 16:48 UTC, MariaShymko commented on module-1/classification.js
> +	    gradeOfStudent = Math.floor(0.1*score - 4);
@szikszail I've added new solution, please review

2019-08-10 13:15 UTC, szikszail reviewed
Nice solution. I am waiting for your next implementations.

2019-08-10 13:15 UTC, szikszail commented on module-1/classification.js
> +	    Math.pow(
Nice! Please ping me on Skype4Business

2019-08-14 19:02 UTC, MariaShymko commented on module-1/classification.js
> +	    Math.pow(
@szikszail Could you please review the solution for the second module? Thank you!

2019-08-19 15:26 UTC, szikszail reviewed
It would be good to see your solutions for the rest of the tasks :)

2019-08-19 15:26 UTC, szikszail commented on module-2/test/calc.spec.js
> +	it("should have proper value",
Quite interesting formatting :)

2020-01-14 19:26 UTC, szikszail commented
Thank you for your solution!

2020-01-14 19:26 UTC, closed without merging