[SM] Complete tasks for module 1
Idea-Pool/js-webinar pull request #30
Opened 2019-08-06 20:58 UTC by Malahovskys

2019-08-13 19:34 UTC, szikszail commented on module-1/classification.js
> +    gradeOfStudent = score < 0 || score > 100 ? 0 : Math.max(Math.min(Math.floor(score/10-4), 5), 1);
Nice solution, please ping me on Skype4Business

2019-08-13 19:39 UTC, szikszail requested changes
Please check my comments.

2019-08-13 19:39 UTC, szikszail commented on module-1/euclidean.js
> +    if(a <= 0 || b <= 0){
It is quite an interesting implementation of the algorithm. It is not optimal, actually quite expensive.
For example, your algorithm for `euclidean(683,997)` will compute 1 in 996 iterations, although the original algorithm does it in 6.

2019-08-20 13:05 UTC, Malahovskys commented on module-1/classification.js
> +    gradeOfStudent = score < 0 || score > 100 ? 0 : Math.max(Math.min(Math.floor(score/10-4), 5), 1);
Pinged you (Siarhei Malakhouski)

2019-08-20 13:06 UTC, Malahovskys commented on module-1/euclidean.js
> +    if(a <= 0 || b <= 0){
Agree, unfortunately no time to rework.

2020-01-14 19:36 UTC, szikszail commented
Thank you for your solution!

2020-01-14 19:36 UTC, closed without merging