Homework for module 1 added
Idea-Pool/js-webinar pull request #9
Opened 2018-04-19 07:42 UTC by PavloTiutiunnyk

2018-04-27 09:49 UTC, szikszail requested changes

2018-04-27 09:49 UTC, szikszail commented on module-1/fibonacci.js
> +    nThFibonacci = n < 0 || n % 1 !==0 ? 0 : n < 2 ? n : fibonacci(n-1) + fibonacci(n-2);
The `n%1 !== 0` expression is always `false` so irrelevant to you algorithm and can be removed.

2018-04-27 09:49 UTC, szikszail commented on module-1/euclidean.js
> +    gcd = a<0||b<0 || typeof a != "number" || typeof b != "number" ? 0 : a==b ? a : a > b ? euclidean(b, a-b) : euclidean(a, b-a);
First of all, recursion in case of the Euclidean algorithm is not necessary, even makes script less optimal, in terms of memory assumption. Also, in this case checking the validity of the parameters happens in all calls, even though it is only necessary for the first call.
Also, I would put the data type checking at the beginning of the expression, so that short circuit evaluation will end earlier in case of a not-a-number parameter.

2018-04-27 09:49 UTC, szikszail commented on module-1/classification.js
> +    gradeOfStudent = score < 100 && score > 59 ? Math.floor((score-50)/10)+1 : score == 100 ? 5 : score <60 && score>=0 ? 1 : 0;
Could you please try to do it without the conditional expression, only with mathematical functions?

2018-04-29 14:28 UTC, PavloTiutiunnyk commented on module-1/fibonacci.js
> +    nThFibonacci = n < 0 || n % 1 !==0 ? 0 : n < 2 ? n : fibonacci(n-1) + fibonacci(n-2);
I believe it helps to return 0 when input is not valid, for example string or non integer number (e.g. "abc", 2,5)
Still it can be replaced with Number.isInteger(n)

2018-04-30 19:35 UTC, szikszail commented on module-1/fibonacci.js
> +    nThFibonacci = n < 0 || n % 1 !==0 ? 0 : n < 2 ? n : fibonacci(n-1) + fibonacci(n-2);
I see that you are checking whether n is integer, nice.

2018-05-03 15:25 UTC, szikszail approved these changes
Nice!

2018-05-03 15:26 UTC, closed without merging